---

- include_vars: pass.yml

- name: Create a new instance and attaches to a network and to a subnetwork
  os_server:
    state: present
    auth:
      auth_url: "http://asgard.es.datio:15000/v3/"
      username: "jhicar.prd"
      password: "{{ os_password }}"
      project_name: "cop_ansible"
    name: "hicar-instance"
    image: "c60877a1-e7cb-48ad-97b3-143a8e87e808"
    key_name: "hicar_key"
    flavor: "d1.medium"
    nics:
      net-id: "40128f87-4009-4599-a0b6-cdf237842c43"
      net-name: "cop_network"
      net-id: "91d7cb0d-acc5-4141-bfe3-1d611574c3b3"
      net-name: "cop_subnet"
    meta:
      hostname: "hicar-instance"